In [16]:
#Cargar_datos

import pandas as pd
from pathlib import Path

In [17]:
# ====================================================================================================================
#  Lectura de archivo
# ====================================================================================================================


ruta_excel = Path(r"X:\Proyectos Python\MODULO 5 HENRY\PI\Proyecto-Integrador-M5\Base_de_datos.xlsx")

df = pd.read_excel(ruta_excel)

df.head()

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,2024-12-21 11:31:35,3692160.0,10,42,Independiente,8000000,2500000,341296,88.768094,...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,2025-04-22 09:47:35,840000.0,6,60,Empleado,3000000,2000000,124876,95.227787,...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,2026-01-08 12:22:40,5974028.4,10,36,Independiente,4036000,829000,529554,47.613894,...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,2025-08-04 12:04:10,1671240.0,6,48,Empleado,1524547,498000,252420,95.227787,...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,2025-04-26 11:24:26,2781636.0,11,44,Empleado,5000000,4000000,217037,95.227787,...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

In [18]:
# ====================================================================================================================
# Generación del CSV
# ====================================================================================================================

ruta_csv = Path(r"X:\Proyectos Python\MODULO 5 HENRY\PI\Proyecto-Integrador-M5\Base_de_datos.csv")

df.to_csv(ruta_csv, index=False)

print("CSV generado en:", ruta_csv)

CSV generado en: X:\Proyectos Python\MODULO 5 HENRY\PI\Proyecto-Integrador-M5\Base_de_datos.csv

In [22]:
# Carga del dataset desde CSV

df_csv = pd.read_csv(ruta_csv)

df.head()

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,2024-12-21 11:31:35,3692160.0,10,42,Independiente,8000000,2500000,341296,88.768094,...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,2025-04-22 09:47:35,840000.0,6,60,Empleado,3000000,2000000,124876,95.227787,...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,2026-01-08 12:22:40,5974028.4,10,36,Independiente,4036000,829000,529554,47.613894,...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,2025-08-04 12:04:10,1671240.0,6,48,Empleado,1524547,498000,252420,95.227787,...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,2025-04-26 11:24:26,2781636.0,11,44,Empleado,5000000,4000000,217037,95.227787,...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

In [24]:
print(f"Filas: {df_csv.shape[0]}")
print(f"Columnas: {df_csv.shape[1]}")

Filas: 10763
Columnas: 23

In [27]:
#Informacion General

df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10763 entries, 0 to 10762
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tipo_credito                   10763 non-null  int64
 1   fecha_prestamo                 10763 non-null  str
 2   capital_prestado               10763 non-null  float64
 3   plazo_meses                    10763 non-null  int64
 4   edad_cliente                   10763 non-null  int64
 5   tipo_laboral                   10763 non-null  str
 6   salario_cliente                10763 non-null  int64
 7   total_otros_prestamos          10763 non-null  int64
 8   cuota_pactada                  10763 non-null  int64
 9   puntaje                        10763 non-null  float64
 10  puntaje_datacredito            10757 non-null  float64
 11  cant_creditosvigentes          10763 non-null  int64
 12  huella_consulta                10763 non-null  int64
 13  saldo_mora                     10607 non-null  float64
 14  saldo_total                    10607 non-null  float64
 15  saldo_principal                10358 non-null  float64
 16  saldo_mora_codeudor            10173 non-null  float64
 17  creditos_sectorFinanciero      10763 non-null  int64
 18  creditos_sectorCooperativo     10763 non-null  int64
 19  creditos_sectorReal            10763 non-null  int64
 20  promedio_ingresos_datacredito  7833 non-null   float64
 21  tendencia_ingresos             7831 non-null   str
 22  Pago_atiempo                   10763 non-null  int64
dtypes: float64(8), int64(12), str(3)
memory usage: 1.9 MB

In [29]:
# Revision de valores NULOS

df_csv.isnull().sum()

tipo_credito                        0
fecha_prestamo                      0
capital_prestado                    0
plazo_meses                         0
edad_cliente                        0
tipo_laboral                        0
salario_cliente                     0
total_otros_prestamos               0
cuota_pactada                       0
puntaje                             0
puntaje_datacredito                 6
cant_creditosvigentes               0
huella_consulta                     0
saldo_mora                        156
saldo_total                       156
saldo_principal                   405
saldo_mora_codeudor               590
creditos_sectorFinanciero           0
creditos_sectorCooperativo          0
creditos_sectorReal                 0
promedio_ingresos_datacredito    2930
tendencia_ingresos               2932
Pago_atiempo                        0
dtype: int64

In [30]:
df_csv.duplicated().sum()

np.int64(0)